### ISSUE TITLE
com.apple...setrestarget.bak is not moved after install script is ran

### ISSUE THREAD

**Issue by markie-dev** [Diatrus/BetterRes#1]
iPhone 10,4
I am on 12.1.2 running the Rootless Jb

After extracting to /var/mobile I set the permissions to 0777 and try to install the script.

After every command the script outputs
“Defaults//com.apple.iokit.IOMobileGraphicsFamily.plist: No such file or directory”

Any Help?

**Comment by Diatrus** [comment]
Looks like it's not setting the resolution for your phone correctly. Could you run uname -m from SSH and give me the output @markieeee?

**Comment by markie-dev** [comment]
iPhone 10,4 @Diatrus

**Comment by Diatrus** [comment]
@markieeee Can you send the exact log of when you run the install.sh for me?

**Comment by markie-dev** [comment]
Marcuss-iPhone:~ root# clear                      
Marcuss-iPhone:~ root# cd /var/mobile/BetterRes   
<r/mobile/BetterRes root# ./install.sh          
iPhone10,4 detected!
is your default resolution.
Crerating stock IOMobileGraphicsFamily.plist...
cp: Defaults//com.apple.iokit.IOMobileGraphicsFamily.plist: No such file or directory
Default IOMobileGraphicsFamily.plist copied!
Creating SetRes resolution files...
cp: /private/var/mobile/Library/Preferences/com.apple.iokit.IOMobileGraphicsFamily.plist: No such file or directory
cp: /private/var/mobile/Library/Preferences/com.apple.iokit.IOMobileGraphicsFamily.plist: No such file or directory
Copying launchdaemons...
Done! Set your custom resolution in /private/var/mobile/Library/Preferences/com.apple.iokit.IOMobileGraphicsFamily.plist.setrestarget.bak then reboot and rejailbreak!

@Diatrus

**Comment by Diatrus** [comment]
@markieeee fixed in 0.5.2.

**Comment by markie-dev** [comment]
works great, thanks!
